### ISSUE TITLE
Publish to F-droid

### ISSUE THREAD

**Issue by noverby** [Lastaapps/langualgetool-unofficial#1]
If the App is in a working state, then you could consider publishing it to F-droid. I think many users would be interested in using it.

**Comment by Lastaapps** [comment]
Hi, it is kind of working, but it is still unfinished and half backed. When it is finished it will go straight to F-Droid for sure. Currently, it looks as shown below. Later I realized that this format is kind of useless without integration as a system spellchecker, which is still missing. But at least I could publish an alpha release to GitHub, that's true. Unfortunately, I'm not sure how much time can or want I give it right now…

![Screenshot_20240214_160253_LanguageTool](https://github.com/Lastaapps/langualgetool-unofficial/assets/47794319/6b300f80-650c-4884-8ee0-651ba04b86c4)

But if you think enough people would find it useful event without the system spellchecker, I will finish the small bits today/tomorrow and publish it.

**Comment by noverby** [comment]
If spell checking is not integrated into the system yet, then it is probably better to wait.

Anyway, thanks for working on this!  :)

**Comment by Lastaapps** [comment]
Sorry for that, I couldn't find time for this as I miss time for my personal projects 😔

**Comment by noverby** [comment]
@Lastaapps You shouldn't be sorry. Thanks for your work :)
